-- ============================================================
-- Sixtel initial schema
-- ============================================================
--
-- Conventions used throughout:
--   * Primary keys are UUIDs generated by gen_random_uuid().
--     UUIDs are 128-bit identifiers that don't leak ordering or
--     count information the way integer auto-increments do.
--   * Every table has created_at and updated_at columns.
--   * Timestamps are 'timestamptz' (timestamp with time zone),
--     always. Never use plain 'timestamp' — it loses timezone
--     info and is a bug waiting to happen.
--   * Foreign keys cascade on delete only where the child's
--     existence makes no sense without the parent.
--
-- A small trigger at the bottom keeps updated_at fresh.

-- Make sure gen_random_uuid() is available.
create extension if not exists pgcrypto;

-- Reusable trigger function: bumps updated_at on every UPDATE.
create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ------------------------------------------------------------
-- members_cache: read cache of Square loyalty + customer data.
-- ------------------------------------------------------------
-- Square is the source of truth. We cache a denormalized copy
-- so listing the member roster in admin doesn't require N
-- round-trips to Square. Refreshed by webhook and by a nightly
-- reconciliation job.
create table members_cache (
  id                         uuid primary key default gen_random_uuid(),
  square_customer_id         text unique not null,
  square_loyalty_account_id  text unique,
  phone_e164                 text not null,
  display_name               text,
  birthday_month             smallint check (birthday_month between 1 and 12),
  birthday_day               smallint check (birthday_day between 1 and 31),
  signup_anniversary_date    date not null,
  lifetime_points            integer not null default 0,
  current_balance            integer not null default 0,
  last_square_sync_at        timestamptz not null default now(),
  deleted_at                 timestamptz,
  created_at                 timestamptz not null default now(),
  updated_at                 timestamptz not null default now()
);

-- Index for the most common lookup: phone-to-member.
create index members_cache_phone_idx on members_cache (phone_e164);
-- Index for partition: active members only.
create index members_cache_active_idx on members_cache (id) where deleted_at is null;

create trigger members_cache_set_updated_at
  before update on members_cache
  for each row execute function set_updated_at();

-- ------------------------------------------------------------
-- consent_records: durable legal record of marketing consent.
-- ------------------------------------------------------------
-- Append-only. If a member opts out we update revoked_at; we
-- DO NOT delete the row, even on account deletion. This is the
-- artifact we point to if anyone asks "did this person consent?"
create table consent_records (
  id                  uuid primary key default gen_random_uuid(),
  square_customer_id  text not null,
  phone_e164          text not null,
  consent_text        text not null,
  consent_version     text not null,
  source              text not null
    check (source in ('website_signup','pos_signup','import')),
  user_agent          text,
  ip_address          inet,
  granted_at          timestamptz not null,
  revoked_at          timestamptz,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index consent_records_customer_idx on consent_records (square_customer_id);

create trigger consent_records_set_updated_at
  before update on consent_records
  for each row execute function set_updated_at();

-- ------------------------------------------------------------
-- passport_definitions: curated beer-passport challenges.
-- ------------------------------------------------------------
create table passport_definitions (
  id              uuid primary key default gen_random_uuid(),
  slug            text unique not null,
  title           text not null,
  description     text,
  reward_text     text not null,
  reward_type     text not null
    check (reward_type in ('credit','swag','members_only')),
  is_active       boolean not null default true,
  start_at        timestamptz,
  end_at          timestamptz,
  required_count  integer not null check (required_count > 0),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index passport_definitions_active_idx on passport_definitions (id) where is_active;

create trigger passport_definitions_set_updated_at
  before update on passport_definitions
  for each row execute function set_updated_at();

-- ------------------------------------------------------------
-- passport_criteria: what counts toward each passport.
-- ------------------------------------------------------------
create table passport_criteria (
  id           uuid primary key default gen_random_uuid(),
  passport_id  uuid not null references passport_definitions(id) on delete cascade,
  match_type   text not null check (match_type in ('style','brewery','item_sku')),
  match_value  text not null,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index passport_criteria_passport_idx on passport_criteria (passport_id);
create index passport_criteria_lookup_idx on passport_criteria (match_type, match_value);

create trigger passport_criteria_set_updated_at
  before update on passport_criteria
  for each row execute function set_updated_at();

-- ------------------------------------------------------------
-- passport_progress: log of credits toward member passports.
-- ------------------------------------------------------------
-- The UNIQUE constraint on (passport_id, source_event_id) is the
-- thing that makes this safe under webhook retries. If Square
-- delivers the same loyalty event twice, the second insert
-- conflicts on the unique key and we discard it.
create table passport_progress (
  id              uuid primary key default gen_random_uuid(),
  member_cache_id uuid not null references members_cache(id) on delete cascade,
  passport_id     uuid not null references passport_definitions(id) on delete cascade,
  source          text not null check (source in ('pos_order_line','staff_stamp')),
  source_event_id text not null,
  awarded_at      timestamptz not null default now(),
  notes           text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (passport_id, source_event_id)
);

create index passport_progress_member_idx on passport_progress (member_cache_id, passport_id);

create trigger passport_progress_set_updated_at
  before update on passport_progress
  for each row execute function set_updated_at();

-- ------------------------------------------------------------
-- passport_completions: one row per (member, passport) finished.
-- ------------------------------------------------------------
create table passport_completions (
  id               uuid primary key default gen_random_uuid(),
  member_cache_id  uuid not null references members_cache(id) on delete cascade,
  passport_id      uuid not null references passport_definitions(id) on delete cascade,
  completed_at     timestamptz not null default now(),
  reward_delivery  text not null,
  reward_notes     text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (member_cache_id, passport_id)
);

create index passport_completions_member_idx on passport_completions (member_cache_id);

create trigger passport_completions_set_updated_at
  before update on passport_completions
  for each row execute function set_updated_at();

-- ------------------------------------------------------------
-- events: live music and special-event calendar.
-- ------------------------------------------------------------
create table events (
  id                uuid primary key default gen_random_uuid(),
  title             text not null,
  description       text,
  starts_at         timestamptz not null,
  ends_at           timestamptz,
  is_members_only   boolean not null default false,
  cover_image_path  text,
  external_rsvp_url text,
  published         boolean not null default false,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create index events_upcoming_idx on events (starts_at) where published;

create trigger events_set_updated_at
  before update on events
  for each row execute function set_updated_at();

-- ------------------------------------------------------------
-- event_rsvps: members RSVP'ing to events.
-- ------------------------------------------------------------
create table event_rsvps (
  id              uuid primary key default gen_random_uuid(),
  event_id        uuid not null references events(id) on delete cascade,
  member_cache_id uuid not null references members_cache(id) on delete cascade,
  rsvp_state      text not null check (rsvp_state in ('going','interested','cancelled')),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (event_id, member_cache_id)
);

create index event_rsvps_event_idx on event_rsvps (event_id);
create index event_rsvps_member_idx on event_rsvps (member_cache_id);

create trigger event_rsvps_set_updated_at
  before update on event_rsvps
  for each row execute function set_updated_at();

-- ------------------------------------------------------------
-- tap_list_items: cached/manually-entered tap list.
-- ------------------------------------------------------------
create table tap_list_items (
  id                 uuid primary key default gen_random_uuid(),
  position           smallint not null,
  name               text not null,
  brewery            text,
  style              text,
  abv_percent        numeric(4,2),
  ibu                smallint,
  label_image_url    text,
  source             text not null check (source in ('ufb','manual')),
  source_external_id text,
  is_visible         boolean not null default true,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index tap_list_visible_idx on tap_list_items (position) where is_visible;

create trigger tap_list_items_set_updated_at
  before update on tap_list_items
  for each row execute function set_updated_at();

-- ------------------------------------------------------------
-- webhook_events: every Square webhook, for idempotency + audit.
-- ------------------------------------------------------------
-- The UNIQUE on square_event_id is the safety net. When Square
-- retries a delivery (network blip, our handler returned 5xx),
-- the second insert conflicts and we know it's a duplicate.
create table webhook_events (
  id              uuid primary key default gen_random_uuid(),
  square_event_id text unique not null,
  event_type      text not null,
  received_at     timestamptz not null default now(),
  payload         jsonb not null,
  processed_at    timestamptz,
  process_error   text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index webhook_events_unprocessed_idx on webhook_events (received_at) where processed_at is null;
create index webhook_events_type_idx on webhook_events (event_type, received_at desc);

create trigger webhook_events_set_updated_at
  before update on webhook_events
  for each row execute function set_updated_at();

-- ------------------------------------------------------------
-- admin_profiles: extends Supabase Auth users with our role.
-- ------------------------------------------------------------
-- The id column references auth.users(id) — Supabase Auth manages
-- the actual user records (email, password hash, last sign-in
-- time), and we attach our own per-admin fields here.
create table admin_profiles (
  id           uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  role         text not null check (role in ('owner','staff')),
  is_active    boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create trigger admin_profiles_set_updated_at
  before update on admin_profiles
  for each row execute function set_updated_at();

-- ------------------------------------------------------------
-- admin_adjustments: audit log of admin point changes.
-- ------------------------------------------------------------
create table admin_adjustments (
  id              uuid primary key default gen_random_uuid(),
  admin_user_id   uuid not null references auth.users(id),
  member_cache_id uuid not null references members_cache(id),
  points_delta    integer not null,
  reason          text not null,
  square_event_id text,
  performed_at    timestamptz not null default now(),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index admin_adjustments_member_idx on admin_adjustments (member_cache_id, performed_at desc);
create index admin_adjustments_admin_idx on admin_adjustments (admin_user_id, performed_at desc);

create trigger admin_adjustments_set_updated_at
  before update on admin_adjustments
  for each row execute function set_updated_at();
